version: '2'
services:
  cron:
    scale: 1
    start_on_create: true
  fpm:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  migrations:
    scale: 1
    start_on_create: true
  reset-database:
    scale: 1
    start_on_create: true
  db:
    hostname: my-instance.us-east-1.rds.amazonaws.com
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
  queue:
    scale: 1
    start_on_create: true
  load-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
